name       : allegro4
version    : 4.4.2
release    : 4
source     :
    - http://cdn.allegro.cc/file/library/allegro/4.4.2/allegro-4.4.2.tar.gz : 1b21e7577dbfada02d85ca4510bd22fedaa6ce76fde7f4838c7c1276eb840fdc
license    : Giftware
component  : programming
summary    : Allegro is a cross-platform library mainly aimed at video game and multimedia
    programming.
description: |
    Allegro is a cross-platform library mainly aimed at video game and multimedia programming.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gl)
    - pkgconfig(glu)
    - pkgconfig(libpng)
    - pkgconfig(ogg)
    - pkgconfig(xcursor)
    - pkgconfig(xpm)
    - pkgconfig(xxf86dga)
    - pkgconfig(xxf86vm)
setup      : |
    %cmake \
        -DLIB_SUFFIX=64 \
        -DCMAKE_INSTALL_LIBDIR=%libdir% \
        -DWANT_DOCS=off \
        -DWANT_EXAMPLES=off \
        -DWANT_TOOLS=off \
        -DWANT_TESTS=off
build      : |
    %make
install    : |
    %make_install
